variable_1 = input("adjective: ")
variable_2 = input("noun: ")
variable_3 = input("place: ")
variable_4 = input("noun: ")
variable_11 = input("emotion: ")
variable_5 = input("present verb: ")
variable_6 = input("place: ")
variable_7 = input("number: ")
variable_8 = input("plural noun: ")
variable_9 = input("present verb: ")
variable_10 = input("adjective: ")
print("One day, a "+variable_1 +" "+variable_2+" was walking to the "+variable_3+" when he realized he had forgotten his "+variable_4+". That made him really "+variable_11+" because it was his birthday and he really needed his "+variable_4+". He decided to "+variable_5+" back to the "+variable_6+" to see if he had left it there. Unfortunately, when he arrived at "+variable_6+" it was blocked with "+variable_7+" "+variable_8+". He really needed his "+variable_4+" so he decided to "+variable_9+" until he moved the "+variable_8+"."+" He succeeded! Overall, it was a very "+variable_10+" day!")
